// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type Admin struct {
	ID        int32        `json:"id"`
	Username  string       `json:"username"`
	Password  string       `json:"password"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Category struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	Description sql.NullString `json:"description"`
	SortOrder   sql.NullInt32  `json:"sort_order"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Medium struct {
	ID           int32          `json:"id"`
	Filename     string         `json:"filename"`
	OriginalName string         `json:"original_name"`
	Path         string         `json:"path"`
	Url          string         `json:"url"`
	MimeType     sql.NullString `json:"mime_type"`
	Size         sql.NullInt64  `json:"size"`
	Width        sql.NullInt32  `json:"width"`
	Height       sql.NullInt32  `json:"height"`
	CreatedAt    sql.NullTime   `json:"created_at"`
}

type Post struct {
	ID          int32          `json:"id"`
	Title       string         `json:"title"`
	Slug        string         `json:"slug"`
	Content     string         `json:"content"`
	Excerpt     sql.NullString `json:"excerpt"`
	CategoryID  sql.NullInt32  `json:"category_id"`
	Status      sql.NullString `json:"status"`
	ViewCount   sql.NullInt32  `json:"view_count"`
	ReadingTime sql.NullInt32  `json:"reading_time"`
	Thumbnail   sql.NullString `json:"thumbnail"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	PublishedAt sql.NullTime   `json:"published_at"`
}

type PostTag struct {
	PostID int32 `json:"post_id"`
	TagID  int32 `json:"tag_id"`
}

type Project struct {
	ID          int32                 `json:"id"`
	Title       string                `json:"title"`
	Slug        string                `json:"slug"`
	Description sql.NullString        `json:"description"`
	Content     sql.NullString        `json:"content"`
	TechStack   pqtype.NullRawMessage `json:"tech_stack"`
	DemoUrl     sql.NullString        `json:"demo_url"`
	GithubUrl   sql.NullString        `json:"github_url"`
	Thumbnail   sql.NullString        `json:"thumbnail"`
	Images      pqtype.NullRawMessage `json:"images"`
	IsFeatured  sql.NullBool          `json:"is_featured"`
	SortOrder   sql.NullInt32         `json:"sort_order"`
	CreatedAt   sql.NullTime          `json:"created_at"`
	UpdatedAt   sql.NullTime          `json:"updated_at"`
}

type Tag struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	Slug      string       `json:"slug"`
	CreatedAt sql.NullTime `json:"created_at"`
}
