// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddPostTag(ctx context.Context, arg AddPostTagParams) error
	CheckSlugExists(ctx context.Context, slug string) (bool, error)
	CheckSlugExistsExcept(ctx context.Context, arg CheckSlugExistsExceptParams) (bool, error)
	CountAllPosts(ctx context.Context) (int64, error)
	CountMedia(ctx context.Context) (int64, error)
	CountPostsByStatus(ctx context.Context, status sql.NullString) (int64, error)
	CountPublishedPosts(ctx context.Context) (int64, error)
	CountPublishedPostsByCategory(ctx context.Context, categoryID sql.NullInt32) (int64, error)
	CountPublishedPostsByTag(ctx context.Context, tagID int32) (int64, error)
	CountSearchPublishedPosts(ctx context.Context, dollar_1 sql.NullString) (int64, error)
	CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateMedia(ctx context.Context, arg CreateMediaParams) (Medium, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	DeleteCategory(ctx context.Context, id int32) error
	DeleteMedia(ctx context.Context, id int32) error
	DeletePost(ctx context.Context, id int32) error
	DeleteProject(ctx context.Context, id int32) error
	DeleteTag(ctx context.Context, id int32) error
	GetAdminByID(ctx context.Context, id int32) (Admin, error)
	// Blog API SQL Queries
	// This file contains all SQL queries for sqlc code generation
	// ============================================================================
	// ADMINS
	// ============================================================================
	GetAdminByUsername(ctx context.Context, username string) (Admin, error)
	GetCategoryByID(ctx context.Context, id int32) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetCategoryPostCount(ctx context.Context, categoryID sql.NullInt32) (int64, error)
	GetCategoryStats(ctx context.Context) ([]GetCategoryStatsRow, error)
	GetMediaByID(ctx context.Context, id int32) (Medium, error)
	GetPostByID(ctx context.Context, id int32) (GetPostByIDRow, error)
	GetPostBySlug(ctx context.Context, slug string) (GetPostBySlugRow, error)
	// ============================================================================
	// DASHBOARD STATS
	// ============================================================================
	GetPostStats(ctx context.Context) (GetPostStatsRow, error)
	// ============================================================================
	// POST_TAGS
	// ============================================================================
	GetPostTags(ctx context.Context, postID int32) ([]Tag, error)
	GetProjectByID(ctx context.Context, id int32) (Project, error)
	GetProjectBySlug(ctx context.Context, slug string) (Project, error)
	GetPublishedPostBySlug(ctx context.Context, slug string) (GetPublishedPostBySlugRow, error)
	GetRecentPosts(ctx context.Context, limit int32) ([]GetRecentPostsRow, error)
	GetTagByID(ctx context.Context, id int32) (Tag, error)
	GetTagBySlug(ctx context.Context, slug string) (Tag, error)
	GetTagPostCount(ctx context.Context, tagID int32) (int64, error)
	GetTotalViews(ctx context.Context) (interface{}, error)
	IncrementViewCount(ctx context.Context, id int32) error
	ListAllPosts(ctx context.Context, arg ListAllPostsParams) ([]ListAllPostsRow, error)
	// ============================================================================
	// CATEGORIES
	// ============================================================================
	ListCategories(ctx context.Context) ([]Category, error)
	ListFeaturedProjects(ctx context.Context) ([]Project, error)
	// ============================================================================
	// MEDIA
	// ============================================================================
	ListMedia(ctx context.Context, arg ListMediaParams) ([]Medium, error)
	ListPostsByStatus(ctx context.Context, arg ListPostsByStatusParams) ([]ListPostsByStatusRow, error)
	// ============================================================================
	// PROJECTS
	// ============================================================================
	ListProjects(ctx context.Context) ([]Project, error)
	// ============================================================================
	// POSTS
	// ============================================================================
	ListPublishedPosts(ctx context.Context, arg ListPublishedPostsParams) ([]ListPublishedPostsRow, error)
	ListPublishedPostsByCategory(ctx context.Context, arg ListPublishedPostsByCategoryParams) ([]ListPublishedPostsByCategoryRow, error)
	ListPublishedPostsByTag(ctx context.Context, arg ListPublishedPostsByTagParams) ([]ListPublishedPostsByTagRow, error)
	// ============================================================================
	// TAGS
	// ============================================================================
	ListTags(ctx context.Context) ([]Tag, error)
	ListTagsWithPostCount(ctx context.Context) ([]ListTagsWithPostCountRow, error)
	PublishPost(ctx context.Context, id int32) (Post, error)
	RemoveAllPostTags(ctx context.Context, postID int32) error
	RemovePostTag(ctx context.Context, arg RemovePostTagParams) error
	SearchPublishedPosts(ctx context.Context, arg SearchPublishedPostsParams) ([]SearchPublishedPostsRow, error)
	SetPostTags(ctx context.Context, postID int32) error
	UnpublishPost(ctx context.Context, id int32) (Post, error)
	UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectOrder(ctx context.Context, arg UpdateProjectOrderParams) error
	UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error)
}

var _ Querier = (*Queries)(nil)
